# Generates the x64 build from the Win32 projects: neo\doom-x64.sln with idlib-x64, game-x64 and
# doom3-x64 (.vcxproj). The VS2010-era Win32 projects stay untouched: they are the editor build.
#
#   python tools\gen-x64-projects.py            (re-run after adding source files to a Win32 project)
#
# What the x64 build is (CLAUDE.md, Stage 1):
#   - the file list of Release|Win32, minus the MFC tools, the x86 inline-asm SIMD back ends and curl
#   - defines: ID_NO_TOOLS (BuildDefines.h), ID_ENABLE_CURL=0, ID_OPENAL=0 (no x64 OpenAL/EAX libs here),
#     ID_SW_RENDERER (exe only: the hooks of renderer\sw in the engine's files)
#   - no _USE_32BIT_TIME_T (illegal on x64), no eaxguid/openal libs
#   - the software rasterizer core neo\renderer\sw\sw_core.c compiled as C with /arch:AVX512
#   - outputs build\x64\<Config>\DOOM3.exe and gamex64.dll
import os
import uuid
import xml.etree.ElementTree as ET

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'neo'))
NS = {'m': 'http://schemas.microsoft.com/developer/msbuild/2003'}
BS = chr(92)


def norm(p):
    return p.replace('/', BS)


def source_files(proj):
    """(path, createsPch) of every ClCompile item that Release|Win32 builds"""
    root = ET.parse(os.path.join(ROOT, proj)).getroot()
    out = []
    for it in root.findall('.//m:ClCompile[@Include]', NS):
        excluded, creates = False, False
        for ch in it:
            tag = ch.tag.split('}')[1]
            cond = ch.get('Condition', '')
            if cond and "'Release|Win32'" not in cond:
                continue
            text = (ch.text or '').strip()
            if tag == 'ExcludedFromBuild' and text.lower() == 'true':
                excluded = True
            if tag == 'PrecompiledHeader' and text == 'Create':
                creates = True
        if not excluded:
            out.append((norm(it.get('Include')), creates))
    headers = [norm(h.get('Include')) for h in root.findall('.//m:ClInclude[@Include]', NS)]
    return out, headers


def excluded_x64(path):
    p = path.lower()
    if p.startswith('tools' + BS) and not p.endswith('edit_stub.cpp') and not p.startswith('tools' + BS + 'compilers' + BS):
        return True                                          # the MFC editors stay Win32; dmap, AAS, renderbump, RoQ stay in
    base = p.rsplit(BS, 1)[-1]
    if base in ('simd_sse.cpp', 'simd_sse2.cpp', 'simd_sse3.cpp', 'simd_mmx.cpp', 'simd_3dnow.cpp', 'simd_altivec.cpp'):
        return True                                          # 1,574 x86 inline-asm sites
    if p.startswith('curl' + BS):
        return True
    if base == 'win_cpu.cpp':
        return True                                          # x87 / cpuid inline asm: win_cpu_x64.cpp instead
    return False


CONFIGS = ['Debug', 'Release']


def project_xml(name, guid, kind, files, headers, defines, includes, extra_items='', link='', pch='NotUsing'):
    cfg_items = ''.join(
        f'    <ProjectConfiguration Include="{c}|x64">\n      <Configuration>{c}</Configuration>\n      <Platform>x64</Platform>\n    </ProjectConfiguration>\n'
        for c in CONFIGS)
    cfg_type = {'lib': 'StaticLibrary', 'dll': 'DynamicLibrary', 'exe': 'Application'}[kind]
    compile_items = []
    for path, creates in files:
        if creates:
            compile_items.append(f'    <ClCompile Include="{path}">\n      <PrecompiledHeader>Create</PrecompiledHeader>\n    </ClCompile>\n')
        else:
            compile_items.append(f'    <ClCompile Include="{path}" />\n')
    header_items = ''.join(f'    <ClInclude Include="{h}" />\n' for h in headers)
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools\\gen-x64-projects.py from the Win32 project: edit the generator, not this file. -->
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
{cfg_items}  </ItemGroup>
  <PropertyGroup Label="Globals">
    <ProjectGuid>{{{guid}}}</ProjectGuid>
    <RootNamespace>{name}</RootNamespace>
    <Keyword>Win32Proj</Keyword>
    <!-- the 32-bit-hosted cl.exe dies (0xC0000005) on the rasterizer core's inlining; use the 64-bit host -->
    <PreferredToolArchitecture>x64</PreferredToolArchitecture>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.Default.props" />
  <PropertyGroup Label="Configuration">
    <ConfigurationType>{cfg_type}</ConfigurationType>
    <CharacterSet>MultiByte</CharacterSet>
    <UseOfMfc>false</UseOfMfc>
    <UseDebugLibraries Condition="'$(Configuration)'=='Debug'">true</UseDebugLibraries>
    <WholeProgramOptimization>false</WholeProgramOptimization>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.props" />
  <PropertyGroup>
    <OutDir>..\\build\\x64\\$(Configuration)\\</OutDir>
    <IntDir>..\\build\\x64\\$(Configuration)\\intermediate\\{name}\\</IntDir>
    <LinkIncremental>false</LinkIncremental>
    <GenerateManifest>true</GenerateManifest>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <PreprocessorDefinitions>WIN32;_WINDOWS;_CRT_SECURE_NO_DEPRECATE;_CRT_NONSTDC_NO_DEPRECATE;_ALLOW_KEYWORD_MACROS;ID_NO_TOOLS;ID_ENABLE_CURL=0;ID_OPENAL=0;{defines};%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalIncludeDirectories>{includes}%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <WarningLevel>Level3</WarningLevel>
      <TreatSpecificWarningsAsErrors>4311;4312;4302</TreatSpecificWarningsAsErrors>
      <DisableSpecificWarnings>4267;4244;4305;4018;4838;5208;4099</DisableSpecificWarnings>
      <PrecompiledHeader>{pch}</PrecompiledHeader>
      <PrecompiledHeaderFile></PrecompiledHeaderFile>
      <RuntimeTypeInfo>true</RuntimeTypeInfo>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <FloatingPointModel>Fast</FloatingPointModel>
      <StringPooling>true</StringPooling>
      <ConformanceMode>false</ConformanceMode>
      <LanguageStandard>stdcpp14</LanguageStandard>
      <AdditionalOptions>/Zc:strictStrings- /Zc:forScope- %(AdditionalOptions)</AdditionalOptions>
      <Optimization Condition="'$(Configuration)'=='Release'">MaxSpeed</Optimization>
      <Optimization Condition="'$(Configuration)'=='Debug'">Disabled</Optimization>
      <InlineFunctionExpansion Condition="'$(Configuration)'=='Release'">AnySuitable</InlineFunctionExpansion>
      <IntrinsicFunctions Condition="'$(Configuration)'=='Release'">true</IntrinsicFunctions>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <BufferSecurityCheck>false</BufferSecurityCheck>
      <RuntimeLibrary Condition="'$(Configuration)'=='Release'">MultiThreaded</RuntimeLibrary>
      <RuntimeLibrary Condition="'$(Configuration)'=='Debug'">MultiThreadedDebug</RuntimeLibrary>
      <PreprocessorDefinitions Condition="'$(Configuration)'=='Release'">NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <PreprocessorDefinitions Condition="'$(Configuration)'=='Debug'">_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
    <Link>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <OptimizeReferences Condition="'$(Configuration)'=='Release'">true</OptimizeReferences>
      <EnableCOMDATFolding Condition="'$(Configuration)'=='Release'">true</EnableCOMDATFolding>
{link}    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
{''.join(compile_items)}{extra_items}  </ItemGroup>
  <ItemGroup>
{header_items}  </ItemGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.targets" />
</Project>
'''


def main():
    guids = {n: str(uuid.uuid5(uuid.NAMESPACE_URL, 'doom3-x64/' + n)).upper() for n in ('idlib-x64', 'game-x64', 'game-d3xp-x64', 'doom3-x64')}

    # idlib
    files, headers = source_files('idlib.vcxproj')
    files = [(p, c) for p, c in files if not excluded_x64(p)]
    open(os.path.join(ROOT, 'idlib-x64.vcxproj'), 'w', encoding='utf-8', newline='\r\n').write(
        project_xml('idlib-x64', guids['idlib-x64'], 'lib', files, headers, '__IDLIB__', '', pch='Use'))
    print('idlib-x64:', len(files), 'files')

    # game
    files, headers = source_files('game.vcxproj')
    link = ('      <OutputFile>$(OutDir)gamex64.dll</OutputFile>\n'
            '      <ModuleDefinitionFile>.\\game\\game.def</ModuleDefinitionFile>\n'
            '      <AdditionalDependencies>$(OutDir)idlib-x64.lib;%(AdditionalDependencies)</AdditionalDependencies>\n')
    open(os.path.join(ROOT, 'game-x64.vcxproj'), 'w', encoding='utf-8', newline='\r\n').write(
        project_xml('game-x64', guids['game-x64'], 'dll', files, headers, '__DOOM__;GAME_DLL', '', link=link))
    print('game-x64:', len(files), 'files')

    # Resurrection of Evil: the same game code tree under d3xp, its DLL in a directory of its own
    # (FindDLL looks in <exe dir>/<fs_game>/ first on x64)
    files, headers = source_files('game-d3xp.vcxproj')
    link = ('      <OutputFile>$(OutDir)d3xp\\gamex64.dll</OutputFile>\n'
            '      <ModuleDefinitionFile>.\\d3xp\\game.def</ModuleDefinitionFile>\n'
            '      <AdditionalDependencies>$(OutDir)idlib-x64.lib;%(AdditionalDependencies)</AdditionalDependencies>\n')
    open(os.path.join(ROOT, 'game-d3xp-x64.vcxproj'), 'w', encoding='utf-8', newline='\r\n').write(
        project_xml('game-d3xp-x64', guids['game-d3xp-x64'], 'dll', files, headers, '__DOOM__;GAME_DLL;_D3XP;CTF', '', link=link))
    print('game-d3xp-x64:', len(files), 'files')

    # engine
    files, headers = source_files('doomdll.vcxproj')
    kept = [(p, c) for p, c in files if not excluded_x64(p)]
    dropped = [p for p, c in files if excluded_x64(p)]
    have = {p.lower() for p, _ in kept}
    for stub in ('tools' + BS + 'edit_stub.cpp', 'sys' + BS + 'win32' + BS + 'win_cpu_x64.cpp'):
        if stub.lower() not in have:
            kept.append((stub, False))
    sw = []
    for extra in ('renderer\\sw\\sw_backend.cpp', 'renderer\\sw\\sw_submit.cpp', 'renderer\\sw\\sw_image.cpp', 'renderer\\sw\\sw_present.cpp',
                  'renderer\\sw\\sw_present_native.cpp'):
        if os.path.exists(os.path.join(ROOT, extra)) and extra.lower() not in have:
            kept.append((extra, False))
    # the C core: its own flags, no precompiled header, the only file with /arch:AVX512 (plan 6.2)
    extra_items = ('    <ClCompile Include="renderer\\sw\\sw_core.c">\n'
                   '      <CompileAs>CompileAsC</CompileAs>\n'
                   # measurement builds: set SW_CORE_DEFINES=SW_ORACLES=1 (semicolon separated) and regenerate
                   + ('      <PreprocessorDefinitions>' + os.environ['SW_CORE_DEFINES'] + ';%(PreprocessorDefinitions)</PreprocessorDefinitions>\n'
                      if os.environ.get('SW_CORE_DEFINES') else '') +
                   '      <PrecompiledHeader>NotUsing</PrecompiledHeader>\n'
                   '      <EnableEnhancedInstructionSet>AdvancedVectorExtensions512</EnableEnhancedInstructionSet>\n'
                   '      <Optimization>MaxSpeed</Optimization>\n'
                   '      <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>\n'
                   '      <IntrinsicFunctions>true</IntrinsicFunctions>\n'
                   '      <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>\n'
                   '      <BasicRuntimeChecks>Default</BasicRuntimeChecks>\n'
                   '      <LanguageStandard_C>stdc11</LanguageStandard_C>\n'
                   # without it the optimizer dies in raster_tri (C1001) once the core is big enough;
                   # the kernel benches are the same with and without it (harness, 2026-09-21)
                   '      <AdditionalOptions>/d2SSAOptimizer-</AdditionalOptions>\n'
                   '      <RuntimeTypeInfo>false</RuntimeTypeInfo>\n'
                   # /GS- (the engine's setting) is an internal compiler error in raster_tri with toolset 14.51
                   '      <BufferSecurityCheck>true</BufferSecurityCheck>\n'
                   '      <StringPooling>false</StringPooling>\n'
                   '    </ClCompile>\n')
    link = ('      <OutputFile>$(OutDir)DOOM3.exe</OutputFile>\n'
            '      <SubSystem>Windows</SubSystem>\n'
            '      <StackReserveSize>16777216</StackReserveSize>\n'
            '      <StackCommitSize>16777216</StackCommitSize>\n'
            '      <AdditionalDependencies>$(OutDir)idlib-x64.lib;dbghelp.lib;dinput8.lib;dsound.lib;dxguid.lib;glu32.lib;iphlpapi.lib;opengl32.lib;winmm.lib;wsock32.lib;ws2_32.lib;delayimp.lib;%(AdditionalDependencies)</AdditionalDependencies>\n'
            # Stage 9: r_swRenderer 2 must never load opengl32.dll, while r_swRenderer 0 / 1 (the reference image) still
            # need it; d3d12 / dxgi (the GL-free presenter) must not keep the exe from starting where they are missing
            '      <DelayLoadDLLs>opengl32.dll;glu32.dll;d3d12.dll;dxgi.dll</DelayLoadDLLs>\n')
    open(os.path.join(ROOT, 'doom3-x64.vcxproj'), 'w', encoding='utf-8', newline='\r\n').write(
        project_xml('doom3-x64', guids['doom3-x64'], 'exe', kept, [h for h in headers if not h.lower().startswith('tools' + BS)],
                    '__DOOM__;__DOOM_DLL__;ID_SW_RENDERER', 'sound/vorbis/include;', extra_items=extra_items, link=link))
    print('doom3-x64:', len(kept), 'files kept,', len(dropped), 'dropped (tools, asm SIMD, curl)')

    # solution
    vc = '8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942'
    lines = ['', 'Microsoft Visual Studio Solution File, Format Version 12.00', '# Visual Studio Version 17']
    deps = {'idlib-x64': [], 'game-x64': ['idlib-x64'], 'game-d3xp-x64': ['idlib-x64'], 'doom3-x64': ['idlib-x64']}
    for n in ('idlib-x64', 'game-x64', 'game-d3xp-x64', 'doom3-x64'):
        lines.append(f'Project("{{{vc}}}") = "{n}", "{n}.vcxproj", "{{{guids[n]}}}"')
        if deps[n]:
            lines.append('\tProjectSection(ProjectDependencies) = postProject')
            for d in deps[n]:
                lines.append(f'\t\t{{{guids[d]}}} = {{{guids[d]}}}')
            lines.append('\tEndProjectSection')
        lines.append('EndProject')
    lines += ['Global', '\tGlobalSection(SolutionConfigurationPlatforms) = preSolution']
    lines += [f'\t\t{c}|x64 = {c}|x64' for c in CONFIGS]
    lines += ['\tEndGlobalSection', '\tGlobalSection(ProjectConfigurationPlatforms) = postSolution']
    for n in guids:
        for c in CONFIGS:
            lines += [f'\t\t{{{guids[n]}}}.{c}|x64.ActiveCfg = {c}|x64', f'\t\t{{{guids[n]}}}.{c}|x64.Build.0 = {c}|x64']
    lines += ['\tEndGlobalSection', 'EndGlobal', '']
    open(os.path.join(ROOT, 'doom-x64.sln'), 'w', encoding='utf-8', newline='\r\n').write('\n'.join(lines))


main()
