/* GENERATED by tools\port-x64\gen_qgl_null.py from QGL_Init: do not edit.
   r_swRenderer 2: no opengl32.dll. Every qgl / qwgl pointer is a no-op that counts its calls;
   QGL_NullReport lists them. One stub per entry point, handed out by name, so an extension
   pointer asked for at run time (GLimp_ExtensionPointer) gets one as well.
   The stub takes no arguments and returns 0 in RAX: valid for every GL signature under the x64
   calling convention (arguments in registers or caller-cleaned stack). x64 only, as is the mode. */

#define QGL_NULL_STUBS 640
static int			qglNullCalls[QGL_NULL_STUBS];
static const char *	qglNullNames[QGL_NULL_STUBS];
static int			qglNullCount;

template< int N > static intptr_t APIENTRY QGL_NullStub( void ) { qglNullCalls[N]++; return 0; }
#define QGL_S8( b ) (void *)&QGL_NullStub< b >, (void *)&QGL_NullStub< b + 1 >, (void *)&QGL_NullStub< b + 2 >, (void *)&QGL_NullStub< b + 3 >, \
	(void *)&QGL_NullStub< b + 4 >, (void *)&QGL_NullStub< b + 5 >, (void *)&QGL_NullStub< b + 6 >, (void *)&QGL_NullStub< b + 7 >
#define QGL_S64( b ) QGL_S8( b ), QGL_S8( b + 8 ), QGL_S8( b + 16 ), QGL_S8( b + 24 ), QGL_S8( b + 32 ), QGL_S8( b + 40 ), QGL_S8( b + 48 ), QGL_S8( b + 56 )
static void * const qglNullStubs[QGL_NULL_STUBS] = {
	QGL_S64( 0 ), QGL_S64( 64 ), QGL_S64( 128 ), QGL_S64( 192 ), QGL_S64( 256 ), QGL_S64( 320 ), QGL_S64( 384 ), QGL_S64( 448 ), QGL_S64( 512 ), QGL_S64( 576 )
};

static void *QGL_NullProc( const char *name ) {
	for ( int i = 0; i < qglNullCount; i++ ) {
		if ( !strcmp( qglNullNames[i], name ) ) {
			return qglNullStubs[i];
		}
	}
	if ( qglNullCount == QGL_NULL_STUBS - 1 ) {
		qglNullNames[qglNullCount] = "(more entry points than stubs)";
		return qglNullStubs[qglNullCount];
	}
	qglNullNames[qglNullCount] = Mem_CopyString( name );		// extension names come from the caller's stack or literals: keep a copy
	return qglNullStubs[qglNullCount++];
}

// ---- the entry points whose answer the engine depends on

static const GLubyte * APIENTRY QGL_NullGetString( GLenum name ) {
	switch ( name ) {
	case GL_VENDOR:		return (const GLubyte *)"DOOM 3 software renderer";
	case GL_RENDERER:	return (const GLubyte *)"AVX-512 tile rasterizer (no OpenGL)";
	case GL_VERSION:	return (const GLubyte *)"1.5 none";
	// what the ARB2 path and the software back end rely on, and nothing else: no texture compression
	// (the CPU twins want RGBA), no vertex buffer objects (the vertex cache stays in CPU memory)
	case GL_EXTENSIONS:	return (const GLubyte *)"GL_ARB_multitexture GL_ARB_texture_env_combine GL_ARB_texture_cube_map "
							"GL_ARB_texture_env_dot3 GL_ARB_texture_env_add GL_ARB_texture_non_power_of_two GL_EXT_stencil_wrap "
							"GL_EXT_stencil_two_side GL_ARB_vertex_program GL_ARB_fragment_program GL_EXT_depth_bounds_test";
	}
	return (const GLubyte *)"";
}

static void APIENTRY QGL_NullGetIntegerv( GLenum pname, GLint *params ) {
	switch ( pname ) {
	case GL_MAX_TEXTURE_SIZE:				*params = 8192; break;
	case GL_MAX_TEXTURE_UNITS_ARB:			*params = 8; break;
	case GL_MAX_TEXTURE_COORDS_ARB:			*params = 8; break;
	case GL_MAX_TEXTURE_IMAGE_UNITS_ARB:	*params = 8; break;
	case GL_PROGRAM_ERROR_POSITION_ARB:		*params = -1; break;	// "the program compiled"
	default:								*params = 0; break;
	}
}

static void APIENTRY QGL_NullGenTextures( GLsizei n, GLuint *textures ) {
	static GLuint next = 1024;		// idImage tells "loaded" from its texnum
	for ( GLsizei i = 0; i < n; i++ ) {
		textures[i] = next++;
	}
}

static PROC WINAPI QGL_NullGetProcAddress( LPCSTR name ) {
	return (PROC)QGL_NullProc( name );
}

bool QGL_InitNull( void ) {
	assert( win32.hinstOpenGL == 0 );
	common->Printf( "...no OpenGL: every qgl entry point is a counted no-op\n" );

	qglAccum = dllAccum = ( decltype( dllAccum ) )QGL_NullProc( "glAccum" );
	qglAlphaFunc = dllAlphaFunc = ( decltype( dllAlphaFunc ) )QGL_NullProc( "glAlphaFunc" );
	qglAreTexturesResident = dllAreTexturesResident = ( decltype( dllAreTexturesResident ) )QGL_NullProc( "glAreTexturesResident" );
	qglArrayElement = dllArrayElement = ( decltype( dllArrayElement ) )QGL_NullProc( "glArrayElement" );
	qglBegin = dllBegin = ( decltype( dllBegin ) )QGL_NullProc( "glBegin" );
	qglBindTexture = dllBindTexture = ( decltype( dllBindTexture ) )QGL_NullProc( "glBindTexture" );
	qglBitmap = dllBitmap = ( decltype( dllBitmap ) )QGL_NullProc( "glBitmap" );
	qglBlendFunc = dllBlendFunc = ( decltype( dllBlendFunc ) )QGL_NullProc( "glBlendFunc" );
	qglCallList = dllCallList = ( decltype( dllCallList ) )QGL_NullProc( "glCallList" );
	qglCallLists = dllCallLists = ( decltype( dllCallLists ) )QGL_NullProc( "glCallLists" );
	qglClear = dllClear = ( decltype( dllClear ) )QGL_NullProc( "glClear" );
	qglClearAccum = dllClearAccum = ( decltype( dllClearAccum ) )QGL_NullProc( "glClearAccum" );
	qglClearColor = dllClearColor = ( decltype( dllClearColor ) )QGL_NullProc( "glClearColor" );
	qglClearDepth = dllClearDepth = ( decltype( dllClearDepth ) )QGL_NullProc( "glClearDepth" );
	qglClearIndex = dllClearIndex = ( decltype( dllClearIndex ) )QGL_NullProc( "glClearIndex" );
	qglClearStencil = dllClearStencil = ( decltype( dllClearStencil ) )QGL_NullProc( "glClearStencil" );
	qglClipPlane = dllClipPlane = ( decltype( dllClipPlane ) )QGL_NullProc( "glClipPlane" );
	qglColor3b = dllColor3b = ( decltype( dllColor3b ) )QGL_NullProc( "glColor3b" );
	qglColor3bv = dllColor3bv = ( decltype( dllColor3bv ) )QGL_NullProc( "glColor3bv" );
	qglColor3d = dllColor3d = ( decltype( dllColor3d ) )QGL_NullProc( "glColor3d" );
	qglColor3dv = dllColor3dv = ( decltype( dllColor3dv ) )QGL_NullProc( "glColor3dv" );
	qglColor3f = dllColor3f = ( decltype( dllColor3f ) )QGL_NullProc( "glColor3f" );
	qglColor3fv = dllColor3fv = ( decltype( dllColor3fv ) )QGL_NullProc( "glColor3fv" );
	qglColor3i = dllColor3i = ( decltype( dllColor3i ) )QGL_NullProc( "glColor3i" );
	qglColor3iv = dllColor3iv = ( decltype( dllColor3iv ) )QGL_NullProc( "glColor3iv" );
	qglColor3s = dllColor3s = ( decltype( dllColor3s ) )QGL_NullProc( "glColor3s" );
	qglColor3sv = dllColor3sv = ( decltype( dllColor3sv ) )QGL_NullProc( "glColor3sv" );
	qglColor3ub = dllColor3ub = ( decltype( dllColor3ub ) )QGL_NullProc( "glColor3ub" );
	qglColor3ubv = dllColor3ubv = ( decltype( dllColor3ubv ) )QGL_NullProc( "glColor3ubv" );
	qglColor3ui = dllColor3ui = ( decltype( dllColor3ui ) )QGL_NullProc( "glColor3ui" );
	qglColor3uiv = dllColor3uiv = ( decltype( dllColor3uiv ) )QGL_NullProc( "glColor3uiv" );
	qglColor3us = dllColor3us = ( decltype( dllColor3us ) )QGL_NullProc( "glColor3us" );
	qglColor3usv = dllColor3usv = ( decltype( dllColor3usv ) )QGL_NullProc( "glColor3usv" );
	qglColor4b = dllColor4b = ( decltype( dllColor4b ) )QGL_NullProc( "glColor4b" );
	qglColor4bv = dllColor4bv = ( decltype( dllColor4bv ) )QGL_NullProc( "glColor4bv" );
	qglColor4d = dllColor4d = ( decltype( dllColor4d ) )QGL_NullProc( "glColor4d" );
	qglColor4dv = dllColor4dv = ( decltype( dllColor4dv ) )QGL_NullProc( "glColor4dv" );
	qglColor4f = dllColor4f = ( decltype( dllColor4f ) )QGL_NullProc( "glColor4f" );
	qglColor4fv = dllColor4fv = ( decltype( dllColor4fv ) )QGL_NullProc( "glColor4fv" );
	qglColor4i = dllColor4i = ( decltype( dllColor4i ) )QGL_NullProc( "glColor4i" );
	qglColor4iv = dllColor4iv = ( decltype( dllColor4iv ) )QGL_NullProc( "glColor4iv" );
	qglColor4s = dllColor4s = ( decltype( dllColor4s ) )QGL_NullProc( "glColor4s" );
	qglColor4sv = dllColor4sv = ( decltype( dllColor4sv ) )QGL_NullProc( "glColor4sv" );
	qglColor4ub = dllColor4ub = ( decltype( dllColor4ub ) )QGL_NullProc( "glColor4ub" );
	qglColor4ubv = dllColor4ubv = ( decltype( dllColor4ubv ) )QGL_NullProc( "glColor4ubv" );
	qglColor4ui = dllColor4ui = ( decltype( dllColor4ui ) )QGL_NullProc( "glColor4ui" );
	qglColor4uiv = dllColor4uiv = ( decltype( dllColor4uiv ) )QGL_NullProc( "glColor4uiv" );
	qglColor4us = dllColor4us = ( decltype( dllColor4us ) )QGL_NullProc( "glColor4us" );
	qglColor4usv = dllColor4usv = ( decltype( dllColor4usv ) )QGL_NullProc( "glColor4usv" );
	qglColorMask = dllColorMask = ( decltype( dllColorMask ) )QGL_NullProc( "glColorMask" );
	qglColorMaterial = dllColorMaterial = ( decltype( dllColorMaterial ) )QGL_NullProc( "glColorMaterial" );
	qglColorPointer = dllColorPointer = ( decltype( dllColorPointer ) )QGL_NullProc( "glColorPointer" );
	qglCopyPixels = dllCopyPixels = ( decltype( dllCopyPixels ) )QGL_NullProc( "glCopyPixels" );
	qglCopyTexImage1D = dllCopyTexImage1D = ( decltype( dllCopyTexImage1D ) )QGL_NullProc( "glCopyTexImage1D" );
	qglCopyTexImage2D = dllCopyTexImage2D = ( decltype( dllCopyTexImage2D ) )QGL_NullProc( "glCopyTexImage2D" );
	qglCopyTexSubImage1D = dllCopyTexSubImage1D = ( decltype( dllCopyTexSubImage1D ) )QGL_NullProc( "glCopyTexSubImage1D" );
	qglCopyTexSubImage2D = dllCopyTexSubImage2D = ( decltype( dllCopyTexSubImage2D ) )QGL_NullProc( "glCopyTexSubImage2D" );
	qglCullFace = dllCullFace = ( decltype( dllCullFace ) )QGL_NullProc( "glCullFace" );
	qglDeleteLists = dllDeleteLists = ( decltype( dllDeleteLists ) )QGL_NullProc( "glDeleteLists" );
	qglDeleteTextures = dllDeleteTextures = ( decltype( dllDeleteTextures ) )QGL_NullProc( "glDeleteTextures" );
	qglDepthFunc = dllDepthFunc = ( decltype( dllDepthFunc ) )QGL_NullProc( "glDepthFunc" );
	qglDepthMask = dllDepthMask = ( decltype( dllDepthMask ) )QGL_NullProc( "glDepthMask" );
	qglDepthRange = dllDepthRange = ( decltype( dllDepthRange ) )QGL_NullProc( "glDepthRange" );
	qglDisable = dllDisable = ( decltype( dllDisable ) )QGL_NullProc( "glDisable" );
	qglDisableClientState = dllDisableClientState = ( decltype( dllDisableClientState ) )QGL_NullProc( "glDisableClientState" );
	qglDrawArrays = dllDrawArrays = ( decltype( dllDrawArrays ) )QGL_NullProc( "glDrawArrays" );
	qglDrawBuffer = dllDrawBuffer = ( decltype( dllDrawBuffer ) )QGL_NullProc( "glDrawBuffer" );
	qglDrawElements = dllDrawElements = ( decltype( dllDrawElements ) )QGL_NullProc( "glDrawElements" );
	qglDrawPixels = dllDrawPixels = ( decltype( dllDrawPixels ) )QGL_NullProc( "glDrawPixels" );
	qglEdgeFlag = dllEdgeFlag = ( decltype( dllEdgeFlag ) )QGL_NullProc( "glEdgeFlag" );
	qglEdgeFlagPointer = dllEdgeFlagPointer = ( decltype( dllEdgeFlagPointer ) )QGL_NullProc( "glEdgeFlagPointer" );
	qglEdgeFlagv = dllEdgeFlagv = ( decltype( dllEdgeFlagv ) )QGL_NullProc( "glEdgeFlagv" );
	qglEnable = dllEnable = ( decltype( dllEnable ) )QGL_NullProc( "glEnable" );
	qglEnableClientState = dllEnableClientState = ( decltype( dllEnableClientState ) )QGL_NullProc( "glEnableClientState" );
	qglEnd = dllEnd = ( decltype( dllEnd ) )QGL_NullProc( "glEnd" );
	qglEndList = dllEndList = ( decltype( dllEndList ) )QGL_NullProc( "glEndList" );
	qglEvalCoord1d = dllEvalCoord1d = ( decltype( dllEvalCoord1d ) )QGL_NullProc( "glEvalCoord1d" );
	qglEvalCoord1dv = dllEvalCoord1dv = ( decltype( dllEvalCoord1dv ) )QGL_NullProc( "glEvalCoord1dv" );
	qglEvalCoord1f = dllEvalCoord1f = ( decltype( dllEvalCoord1f ) )QGL_NullProc( "glEvalCoord1f" );
	qglEvalCoord1fv = dllEvalCoord1fv = ( decltype( dllEvalCoord1fv ) )QGL_NullProc( "glEvalCoord1fv" );
	qglEvalCoord2d = dllEvalCoord2d = ( decltype( dllEvalCoord2d ) )QGL_NullProc( "glEvalCoord2d" );
	qglEvalCoord2dv = dllEvalCoord2dv = ( decltype( dllEvalCoord2dv ) )QGL_NullProc( "glEvalCoord2dv" );
	qglEvalCoord2f = dllEvalCoord2f = ( decltype( dllEvalCoord2f ) )QGL_NullProc( "glEvalCoord2f" );
	qglEvalCoord2fv = dllEvalCoord2fv = ( decltype( dllEvalCoord2fv ) )QGL_NullProc( "glEvalCoord2fv" );
	qglEvalMesh1 = dllEvalMesh1 = ( decltype( dllEvalMesh1 ) )QGL_NullProc( "glEvalMesh1" );
	qglEvalMesh2 = dllEvalMesh2 = ( decltype( dllEvalMesh2 ) )QGL_NullProc( "glEvalMesh2" );
	qglEvalPoint1 = dllEvalPoint1 = ( decltype( dllEvalPoint1 ) )QGL_NullProc( "glEvalPoint1" );
	qglEvalPoint2 = dllEvalPoint2 = ( decltype( dllEvalPoint2 ) )QGL_NullProc( "glEvalPoint2" );
	qglFeedbackBuffer = dllFeedbackBuffer = ( decltype( dllFeedbackBuffer ) )QGL_NullProc( "glFeedbackBuffer" );
	qglFinish = dllFinish = ( decltype( dllFinish ) )QGL_NullProc( "glFinish" );
	qglFlush = dllFlush = ( decltype( dllFlush ) )QGL_NullProc( "glFlush" );
	qglFogf = dllFogf = ( decltype( dllFogf ) )QGL_NullProc( "glFogf" );
	qglFogfv = dllFogfv = ( decltype( dllFogfv ) )QGL_NullProc( "glFogfv" );
	qglFogi = dllFogi = ( decltype( dllFogi ) )QGL_NullProc( "glFogi" );
	qglFogiv = dllFogiv = ( decltype( dllFogiv ) )QGL_NullProc( "glFogiv" );
	qglFrontFace = dllFrontFace = ( decltype( dllFrontFace ) )QGL_NullProc( "glFrontFace" );
	qglFrustum = dllFrustum = ( decltype( dllFrustum ) )QGL_NullProc( "glFrustum" );
	qglGenLists = dllGenLists = ( decltype( dllGenLists ) )QGL_NullProc( "glGenLists" );
	qglGetBooleanv = dllGetBooleanv = ( decltype( dllGetBooleanv ) )QGL_NullProc( "glGetBooleanv" );
	qglGetClipPlane = dllGetClipPlane = ( decltype( dllGetClipPlane ) )QGL_NullProc( "glGetClipPlane" );
	qglGetDoublev = dllGetDoublev = ( decltype( dllGetDoublev ) )QGL_NullProc( "glGetDoublev" );
	qglGetError = dllGetError = ( decltype( dllGetError ) )QGL_NullProc( "glGetError" );
	qglGetFloatv = dllGetFloatv = ( decltype( dllGetFloatv ) )QGL_NullProc( "glGetFloatv" );
	qglGetLightfv = dllGetLightfv = ( decltype( dllGetLightfv ) )QGL_NullProc( "glGetLightfv" );
	qglGetLightiv = dllGetLightiv = ( decltype( dllGetLightiv ) )QGL_NullProc( "glGetLightiv" );
	qglGetMapdv = dllGetMapdv = ( decltype( dllGetMapdv ) )QGL_NullProc( "glGetMapdv" );
	qglGetMapfv = dllGetMapfv = ( decltype( dllGetMapfv ) )QGL_NullProc( "glGetMapfv" );
	qglGetMapiv = dllGetMapiv = ( decltype( dllGetMapiv ) )QGL_NullProc( "glGetMapiv" );
	qglGetMaterialfv = dllGetMaterialfv = ( decltype( dllGetMaterialfv ) )QGL_NullProc( "glGetMaterialfv" );
	qglGetMaterialiv = dllGetMaterialiv = ( decltype( dllGetMaterialiv ) )QGL_NullProc( "glGetMaterialiv" );
	qglGetPixelMapfv = dllGetPixelMapfv = ( decltype( dllGetPixelMapfv ) )QGL_NullProc( "glGetPixelMapfv" );
	qglGetPixelMapuiv = dllGetPixelMapuiv = ( decltype( dllGetPixelMapuiv ) )QGL_NullProc( "glGetPixelMapuiv" );
	qglGetPixelMapusv = dllGetPixelMapusv = ( decltype( dllGetPixelMapusv ) )QGL_NullProc( "glGetPixelMapusv" );
	qglGetPointerv = dllGetPointerv = ( decltype( dllGetPointerv ) )QGL_NullProc( "glGetPointerv" );
	qglGetPolygonStipple = dllGetPolygonStipple = ( decltype( dllGetPolygonStipple ) )QGL_NullProc( "glGetPolygonStipple" );
	qglGetTexEnvfv = dllGetTexEnvfv = ( decltype( dllGetTexEnvfv ) )QGL_NullProc( "glGetTexEnvfv" );
	qglGetTexEnviv = dllGetTexEnviv = ( decltype( dllGetTexEnviv ) )QGL_NullProc( "glGetTexEnviv" );
	qglGetTexGendv = dllGetTexGendv = ( decltype( dllGetTexGendv ) )QGL_NullProc( "glGetTexGendv" );
	qglGetTexGenfv = dllGetTexGenfv = ( decltype( dllGetTexGenfv ) )QGL_NullProc( "glGetTexGenfv" );
	qglGetTexGeniv = dllGetTexGeniv = ( decltype( dllGetTexGeniv ) )QGL_NullProc( "glGetTexGeniv" );
	qglGetTexImage = dllGetTexImage = ( decltype( dllGetTexImage ) )QGL_NullProc( "glGetTexImage" );
	qglGetTexLevelParameterfv = dllGetTexLevelParameterfv = ( decltype( dllGetTexLevelParameterfv ) )QGL_NullProc( "glGetTexLevelParameterfv" );
	qglGetTexLevelParameteriv = dllGetTexLevelParameteriv = ( decltype( dllGetTexLevelParameteriv ) )QGL_NullProc( "glGetTexLevelParameteriv" );
	qglGetTexParameterfv = dllGetTexParameterfv = ( decltype( dllGetTexParameterfv ) )QGL_NullProc( "glGetTexParameterfv" );
	qglGetTexParameteriv = dllGetTexParameteriv = ( decltype( dllGetTexParameteriv ) )QGL_NullProc( "glGetTexParameteriv" );
	qglHint = dllHint = ( decltype( dllHint ) )QGL_NullProc( "glHint" );
	qglIndexMask = dllIndexMask = ( decltype( dllIndexMask ) )QGL_NullProc( "glIndexMask" );
	qglIndexPointer = dllIndexPointer = ( decltype( dllIndexPointer ) )QGL_NullProc( "glIndexPointer" );
	qglIndexd = dllIndexd = ( decltype( dllIndexd ) )QGL_NullProc( "glIndexd" );
	qglIndexdv = dllIndexdv = ( decltype( dllIndexdv ) )QGL_NullProc( "glIndexdv" );
	qglIndexf = dllIndexf = ( decltype( dllIndexf ) )QGL_NullProc( "glIndexf" );
	qglIndexfv = dllIndexfv = ( decltype( dllIndexfv ) )QGL_NullProc( "glIndexfv" );
	qglIndexi = dllIndexi = ( decltype( dllIndexi ) )QGL_NullProc( "glIndexi" );
	qglIndexiv = dllIndexiv = ( decltype( dllIndexiv ) )QGL_NullProc( "glIndexiv" );
	qglIndexs = dllIndexs = ( decltype( dllIndexs ) )QGL_NullProc( "glIndexs" );
	qglIndexsv = dllIndexsv = ( decltype( dllIndexsv ) )QGL_NullProc( "glIndexsv" );
	qglIndexub = dllIndexub = ( decltype( dllIndexub ) )QGL_NullProc( "glIndexub" );
	qglIndexubv = dllIndexubv = ( decltype( dllIndexubv ) )QGL_NullProc( "glIndexubv" );
	qglInitNames = dllInitNames = ( decltype( dllInitNames ) )QGL_NullProc( "glInitNames" );
	qglInterleavedArrays = dllInterleavedArrays = ( decltype( dllInterleavedArrays ) )QGL_NullProc( "glInterleavedArrays" );
	qglIsEnabled = dllIsEnabled = ( decltype( dllIsEnabled ) )QGL_NullProc( "glIsEnabled" );
	qglIsList = dllIsList = ( decltype( dllIsList ) )QGL_NullProc( "glIsList" );
	qglIsTexture = dllIsTexture = ( decltype( dllIsTexture ) )QGL_NullProc( "glIsTexture" );
	qglLightModelf = dllLightModelf = ( decltype( dllLightModelf ) )QGL_NullProc( "glLightModelf" );
	qglLightModelfv = dllLightModelfv = ( decltype( dllLightModelfv ) )QGL_NullProc( "glLightModelfv" );
	qglLightModeli = dllLightModeli = ( decltype( dllLightModeli ) )QGL_NullProc( "glLightModeli" );
	qglLightModeliv = dllLightModeliv = ( decltype( dllLightModeliv ) )QGL_NullProc( "glLightModeliv" );
	qglLightf = dllLightf = ( decltype( dllLightf ) )QGL_NullProc( "glLightf" );
	qglLightfv = dllLightfv = ( decltype( dllLightfv ) )QGL_NullProc( "glLightfv" );
	qglLighti = dllLighti = ( decltype( dllLighti ) )QGL_NullProc( "glLighti" );
	qglLightiv = dllLightiv = ( decltype( dllLightiv ) )QGL_NullProc( "glLightiv" );
	qglLineStipple = dllLineStipple = ( decltype( dllLineStipple ) )QGL_NullProc( "glLineStipple" );
	qglLineWidth = dllLineWidth = ( decltype( dllLineWidth ) )QGL_NullProc( "glLineWidth" );
	qglListBase = dllListBase = ( decltype( dllListBase ) )QGL_NullProc( "glListBase" );
	qglLoadIdentity = dllLoadIdentity = ( decltype( dllLoadIdentity ) )QGL_NullProc( "glLoadIdentity" );
	qglLoadMatrixd = dllLoadMatrixd = ( decltype( dllLoadMatrixd ) )QGL_NullProc( "glLoadMatrixd" );
	qglLoadMatrixf = dllLoadMatrixf = ( decltype( dllLoadMatrixf ) )QGL_NullProc( "glLoadMatrixf" );
	qglLoadName = dllLoadName = ( decltype( dllLoadName ) )QGL_NullProc( "glLoadName" );
	qglLogicOp = dllLogicOp = ( decltype( dllLogicOp ) )QGL_NullProc( "glLogicOp" );
	qglMap1d = dllMap1d = ( decltype( dllMap1d ) )QGL_NullProc( "glMap1d" );
	qglMap1f = dllMap1f = ( decltype( dllMap1f ) )QGL_NullProc( "glMap1f" );
	qglMap2d = dllMap2d = ( decltype( dllMap2d ) )QGL_NullProc( "glMap2d" );
	qglMap2f = dllMap2f = ( decltype( dllMap2f ) )QGL_NullProc( "glMap2f" );
	qglMapGrid1d = dllMapGrid1d = ( decltype( dllMapGrid1d ) )QGL_NullProc( "glMapGrid1d" );
	qglMapGrid1f = dllMapGrid1f = ( decltype( dllMapGrid1f ) )QGL_NullProc( "glMapGrid1f" );
	qglMapGrid2d = dllMapGrid2d = ( decltype( dllMapGrid2d ) )QGL_NullProc( "glMapGrid2d" );
	qglMapGrid2f = dllMapGrid2f = ( decltype( dllMapGrid2f ) )QGL_NullProc( "glMapGrid2f" );
	qglMaterialf = dllMaterialf = ( decltype( dllMaterialf ) )QGL_NullProc( "glMaterialf" );
	qglMaterialfv = dllMaterialfv = ( decltype( dllMaterialfv ) )QGL_NullProc( "glMaterialfv" );
	qglMateriali = dllMateriali = ( decltype( dllMateriali ) )QGL_NullProc( "glMateriali" );
	qglMaterialiv = dllMaterialiv = ( decltype( dllMaterialiv ) )QGL_NullProc( "glMaterialiv" );
	qglMatrixMode = dllMatrixMode = ( decltype( dllMatrixMode ) )QGL_NullProc( "glMatrixMode" );
	qglMultMatrixd = dllMultMatrixd = ( decltype( dllMultMatrixd ) )QGL_NullProc( "glMultMatrixd" );
	qglMultMatrixf = dllMultMatrixf = ( decltype( dllMultMatrixf ) )QGL_NullProc( "glMultMatrixf" );
	qglNewList = dllNewList = ( decltype( dllNewList ) )QGL_NullProc( "glNewList" );
	qglNormal3b = dllNormal3b = ( decltype( dllNormal3b ) )QGL_NullProc( "glNormal3b" );
	qglNormal3bv = dllNormal3bv = ( decltype( dllNormal3bv ) )QGL_NullProc( "glNormal3bv" );
	qglNormal3d = dllNormal3d = ( decltype( dllNormal3d ) )QGL_NullProc( "glNormal3d" );
	qglNormal3dv = dllNormal3dv = ( decltype( dllNormal3dv ) )QGL_NullProc( "glNormal3dv" );
	qglNormal3f = dllNormal3f = ( decltype( dllNormal3f ) )QGL_NullProc( "glNormal3f" );
	qglNormal3fv = dllNormal3fv = ( decltype( dllNormal3fv ) )QGL_NullProc( "glNormal3fv" );
	qglNormal3i = dllNormal3i = ( decltype( dllNormal3i ) )QGL_NullProc( "glNormal3i" );
	qglNormal3iv = dllNormal3iv = ( decltype( dllNormal3iv ) )QGL_NullProc( "glNormal3iv" );
	qglNormal3s = dllNormal3s = ( decltype( dllNormal3s ) )QGL_NullProc( "glNormal3s" );
	qglNormal3sv = dllNormal3sv = ( decltype( dllNormal3sv ) )QGL_NullProc( "glNormal3sv" );
	qglNormalPointer = dllNormalPointer = ( decltype( dllNormalPointer ) )QGL_NullProc( "glNormalPointer" );
	qglOrtho = dllOrtho = ( decltype( dllOrtho ) )QGL_NullProc( "glOrtho" );
	qglPassThrough = dllPassThrough = ( decltype( dllPassThrough ) )QGL_NullProc( "glPassThrough" );
	qglPixelMapfv = dllPixelMapfv = ( decltype( dllPixelMapfv ) )QGL_NullProc( "glPixelMapfv" );
	qglPixelMapuiv = dllPixelMapuiv = ( decltype( dllPixelMapuiv ) )QGL_NullProc( "glPixelMapuiv" );
	qglPixelMapusv = dllPixelMapusv = ( decltype( dllPixelMapusv ) )QGL_NullProc( "glPixelMapusv" );
	qglPixelStoref = dllPixelStoref = ( decltype( dllPixelStoref ) )QGL_NullProc( "glPixelStoref" );
	qglPixelStorei = dllPixelStorei = ( decltype( dllPixelStorei ) )QGL_NullProc( "glPixelStorei" );
	qglPixelTransferf = dllPixelTransferf = ( decltype( dllPixelTransferf ) )QGL_NullProc( "glPixelTransferf" );
	qglPixelTransferi = dllPixelTransferi = ( decltype( dllPixelTransferi ) )QGL_NullProc( "glPixelTransferi" );
	qglPixelZoom = dllPixelZoom = ( decltype( dllPixelZoom ) )QGL_NullProc( "glPixelZoom" );
	qglPointSize = dllPointSize = ( decltype( dllPointSize ) )QGL_NullProc( "glPointSize" );
	qglPolygonMode = dllPolygonMode = ( decltype( dllPolygonMode ) )QGL_NullProc( "glPolygonMode" );
	qglPolygonOffset = dllPolygonOffset = ( decltype( dllPolygonOffset ) )QGL_NullProc( "glPolygonOffset" );
	qglPolygonStipple = dllPolygonStipple = ( decltype( dllPolygonStipple ) )QGL_NullProc( "glPolygonStipple" );
	qglPopAttrib = dllPopAttrib = ( decltype( dllPopAttrib ) )QGL_NullProc( "glPopAttrib" );
	qglPopClientAttrib = dllPopClientAttrib = ( decltype( dllPopClientAttrib ) )QGL_NullProc( "glPopClientAttrib" );
	qglPopMatrix = dllPopMatrix = ( decltype( dllPopMatrix ) )QGL_NullProc( "glPopMatrix" );
	qglPopName = dllPopName = ( decltype( dllPopName ) )QGL_NullProc( "glPopName" );
	qglPrioritizeTextures = dllPrioritizeTextures = ( decltype( dllPrioritizeTextures ) )QGL_NullProc( "glPrioritizeTextures" );
	qglPushAttrib = dllPushAttrib = ( decltype( dllPushAttrib ) )QGL_NullProc( "glPushAttrib" );
	qglPushClientAttrib = dllPushClientAttrib = ( decltype( dllPushClientAttrib ) )QGL_NullProc( "glPushClientAttrib" );
	qglPushMatrix = dllPushMatrix = ( decltype( dllPushMatrix ) )QGL_NullProc( "glPushMatrix" );
	qglPushName = dllPushName = ( decltype( dllPushName ) )QGL_NullProc( "glPushName" );
	qglRasterPos2d = dllRasterPos2d = ( decltype( dllRasterPos2d ) )QGL_NullProc( "glRasterPos2d" );
	qglRasterPos2dv = dllRasterPos2dv = ( decltype( dllRasterPos2dv ) )QGL_NullProc( "glRasterPos2dv" );
	qglRasterPos2f = dllRasterPos2f = ( decltype( dllRasterPos2f ) )QGL_NullProc( "glRasterPos2f" );
	qglRasterPos2fv = dllRasterPos2fv = ( decltype( dllRasterPos2fv ) )QGL_NullProc( "glRasterPos2fv" );
	qglRasterPos2i = dllRasterPos2i = ( decltype( dllRasterPos2i ) )QGL_NullProc( "glRasterPos2i" );
	qglRasterPos2iv = dllRasterPos2iv = ( decltype( dllRasterPos2iv ) )QGL_NullProc( "glRasterPos2iv" );
	qglRasterPos2s = dllRasterPos2s = ( decltype( dllRasterPos2s ) )QGL_NullProc( "glRasterPos2s" );
	qglRasterPos2sv = dllRasterPos2sv = ( decltype( dllRasterPos2sv ) )QGL_NullProc( "glRasterPos2sv" );
	qglRasterPos3d = dllRasterPos3d = ( decltype( dllRasterPos3d ) )QGL_NullProc( "glRasterPos3d" );
	qglRasterPos3dv = dllRasterPos3dv = ( decltype( dllRasterPos3dv ) )QGL_NullProc( "glRasterPos3dv" );
	qglRasterPos3f = dllRasterPos3f = ( decltype( dllRasterPos3f ) )QGL_NullProc( "glRasterPos3f" );
	qglRasterPos3fv = dllRasterPos3fv = ( decltype( dllRasterPos3fv ) )QGL_NullProc( "glRasterPos3fv" );
	qglRasterPos3i = dllRasterPos3i = ( decltype( dllRasterPos3i ) )QGL_NullProc( "glRasterPos3i" );
	qglRasterPos3iv = dllRasterPos3iv = ( decltype( dllRasterPos3iv ) )QGL_NullProc( "glRasterPos3iv" );
	qglRasterPos3s = dllRasterPos3s = ( decltype( dllRasterPos3s ) )QGL_NullProc( "glRasterPos3s" );
	qglRasterPos3sv = dllRasterPos3sv = ( decltype( dllRasterPos3sv ) )QGL_NullProc( "glRasterPos3sv" );
	qglRasterPos4d = dllRasterPos4d = ( decltype( dllRasterPos4d ) )QGL_NullProc( "glRasterPos4d" );
	qglRasterPos4dv = dllRasterPos4dv = ( decltype( dllRasterPos4dv ) )QGL_NullProc( "glRasterPos4dv" );
	qglRasterPos4f = dllRasterPos4f = ( decltype( dllRasterPos4f ) )QGL_NullProc( "glRasterPos4f" );
	qglRasterPos4fv = dllRasterPos4fv = ( decltype( dllRasterPos4fv ) )QGL_NullProc( "glRasterPos4fv" );
	qglRasterPos4i = dllRasterPos4i = ( decltype( dllRasterPos4i ) )QGL_NullProc( "glRasterPos4i" );
	qglRasterPos4iv = dllRasterPos4iv = ( decltype( dllRasterPos4iv ) )QGL_NullProc( "glRasterPos4iv" );
	qglRasterPos4s = dllRasterPos4s = ( decltype( dllRasterPos4s ) )QGL_NullProc( "glRasterPos4s" );
	qglRasterPos4sv = dllRasterPos4sv = ( decltype( dllRasterPos4sv ) )QGL_NullProc( "glRasterPos4sv" );
	qglReadBuffer = dllReadBuffer = ( decltype( dllReadBuffer ) )QGL_NullProc( "glReadBuffer" );
	qglReadPixels = dllReadPixels = ( decltype( dllReadPixels ) )QGL_NullProc( "glReadPixels" );
	qglRectd = dllRectd = ( decltype( dllRectd ) )QGL_NullProc( "glRectd" );
	qglRectdv = dllRectdv = ( decltype( dllRectdv ) )QGL_NullProc( "glRectdv" );
	qglRectf = dllRectf = ( decltype( dllRectf ) )QGL_NullProc( "glRectf" );
	qglRectfv = dllRectfv = ( decltype( dllRectfv ) )QGL_NullProc( "glRectfv" );
	qglRecti = dllRecti = ( decltype( dllRecti ) )QGL_NullProc( "glRecti" );
	qglRectiv = dllRectiv = ( decltype( dllRectiv ) )QGL_NullProc( "glRectiv" );
	qglRects = dllRects = ( decltype( dllRects ) )QGL_NullProc( "glRects" );
	qglRectsv = dllRectsv = ( decltype( dllRectsv ) )QGL_NullProc( "glRectsv" );
	qglRenderMode = dllRenderMode = ( decltype( dllRenderMode ) )QGL_NullProc( "glRenderMode" );
	qglRotated = dllRotated = ( decltype( dllRotated ) )QGL_NullProc( "glRotated" );
	qglRotatef = dllRotatef = ( decltype( dllRotatef ) )QGL_NullProc( "glRotatef" );
	qglScaled = dllScaled = ( decltype( dllScaled ) )QGL_NullProc( "glScaled" );
	qglScalef = dllScalef = ( decltype( dllScalef ) )QGL_NullProc( "glScalef" );
	qglScissor = dllScissor = ( decltype( dllScissor ) )QGL_NullProc( "glScissor" );
	qglSelectBuffer = dllSelectBuffer = ( decltype( dllSelectBuffer ) )QGL_NullProc( "glSelectBuffer" );
	qglShadeModel = dllShadeModel = ( decltype( dllShadeModel ) )QGL_NullProc( "glShadeModel" );
	qglStencilFunc = dllStencilFunc = ( decltype( dllStencilFunc ) )QGL_NullProc( "glStencilFunc" );
	qglStencilMask = dllStencilMask = ( decltype( dllStencilMask ) )QGL_NullProc( "glStencilMask" );
	qglStencilOp = dllStencilOp = ( decltype( dllStencilOp ) )QGL_NullProc( "glStencilOp" );
	qglTexCoord1d = dllTexCoord1d = ( decltype( dllTexCoord1d ) )QGL_NullProc( "glTexCoord1d" );
	qglTexCoord1dv = dllTexCoord1dv = ( decltype( dllTexCoord1dv ) )QGL_NullProc( "glTexCoord1dv" );
	qglTexCoord1f = dllTexCoord1f = ( decltype( dllTexCoord1f ) )QGL_NullProc( "glTexCoord1f" );
	qglTexCoord1fv = dllTexCoord1fv = ( decltype( dllTexCoord1fv ) )QGL_NullProc( "glTexCoord1fv" );
	qglTexCoord1i = dllTexCoord1i = ( decltype( dllTexCoord1i ) )QGL_NullProc( "glTexCoord1i" );
	qglTexCoord1iv = dllTexCoord1iv = ( decltype( dllTexCoord1iv ) )QGL_NullProc( "glTexCoord1iv" );
	qglTexCoord1s = dllTexCoord1s = ( decltype( dllTexCoord1s ) )QGL_NullProc( "glTexCoord1s" );
	qglTexCoord1sv = dllTexCoord1sv = ( decltype( dllTexCoord1sv ) )QGL_NullProc( "glTexCoord1sv" );
	qglTexCoord2d = dllTexCoord2d = ( decltype( dllTexCoord2d ) )QGL_NullProc( "glTexCoord2d" );
	qglTexCoord2dv = dllTexCoord2dv = ( decltype( dllTexCoord2dv ) )QGL_NullProc( "glTexCoord2dv" );
	qglTexCoord2f = dllTexCoord2f = ( decltype( dllTexCoord2f ) )QGL_NullProc( "glTexCoord2f" );
	qglTexCoord2fv = dllTexCoord2fv = ( decltype( dllTexCoord2fv ) )QGL_NullProc( "glTexCoord2fv" );
	qglTexCoord2i = dllTexCoord2i = ( decltype( dllTexCoord2i ) )QGL_NullProc( "glTexCoord2i" );
	qglTexCoord2iv = dllTexCoord2iv = ( decltype( dllTexCoord2iv ) )QGL_NullProc( "glTexCoord2iv" );
	qglTexCoord2s = dllTexCoord2s = ( decltype( dllTexCoord2s ) )QGL_NullProc( "glTexCoord2s" );
	qglTexCoord2sv = dllTexCoord2sv = ( decltype( dllTexCoord2sv ) )QGL_NullProc( "glTexCoord2sv" );
	qglTexCoord3d = dllTexCoord3d = ( decltype( dllTexCoord3d ) )QGL_NullProc( "glTexCoord3d" );
	qglTexCoord3dv = dllTexCoord3dv = ( decltype( dllTexCoord3dv ) )QGL_NullProc( "glTexCoord3dv" );
	qglTexCoord3f = dllTexCoord3f = ( decltype( dllTexCoord3f ) )QGL_NullProc( "glTexCoord3f" );
	qglTexCoord3fv = dllTexCoord3fv = ( decltype( dllTexCoord3fv ) )QGL_NullProc( "glTexCoord3fv" );
	qglTexCoord3i = dllTexCoord3i = ( decltype( dllTexCoord3i ) )QGL_NullProc( "glTexCoord3i" );
	qglTexCoord3iv = dllTexCoord3iv = ( decltype( dllTexCoord3iv ) )QGL_NullProc( "glTexCoord3iv" );
	qglTexCoord3s = dllTexCoord3s = ( decltype( dllTexCoord3s ) )QGL_NullProc( "glTexCoord3s" );
	qglTexCoord3sv = dllTexCoord3sv = ( decltype( dllTexCoord3sv ) )QGL_NullProc( "glTexCoord3sv" );
	qglTexCoord4d = dllTexCoord4d = ( decltype( dllTexCoord4d ) )QGL_NullProc( "glTexCoord4d" );
	qglTexCoord4dv = dllTexCoord4dv = ( decltype( dllTexCoord4dv ) )QGL_NullProc( "glTexCoord4dv" );
	qglTexCoord4f = dllTexCoord4f = ( decltype( dllTexCoord4f ) )QGL_NullProc( "glTexCoord4f" );
	qglTexCoord4fv = dllTexCoord4fv = ( decltype( dllTexCoord4fv ) )QGL_NullProc( "glTexCoord4fv" );
	qglTexCoord4i = dllTexCoord4i = ( decltype( dllTexCoord4i ) )QGL_NullProc( "glTexCoord4i" );
	qglTexCoord4iv = dllTexCoord4iv = ( decltype( dllTexCoord4iv ) )QGL_NullProc( "glTexCoord4iv" );
	qglTexCoord4s = dllTexCoord4s = ( decltype( dllTexCoord4s ) )QGL_NullProc( "glTexCoord4s" );
	qglTexCoord4sv = dllTexCoord4sv = ( decltype( dllTexCoord4sv ) )QGL_NullProc( "glTexCoord4sv" );
	qglTexCoordPointer = dllTexCoordPointer = ( decltype( dllTexCoordPointer ) )QGL_NullProc( "glTexCoordPointer" );
	qglTexEnvf = dllTexEnvf = ( decltype( dllTexEnvf ) )QGL_NullProc( "glTexEnvf" );
	qglTexEnvfv = dllTexEnvfv = ( decltype( dllTexEnvfv ) )QGL_NullProc( "glTexEnvfv" );
	qglTexEnvi = dllTexEnvi = ( decltype( dllTexEnvi ) )QGL_NullProc( "glTexEnvi" );
	qglTexEnviv = dllTexEnviv = ( decltype( dllTexEnviv ) )QGL_NullProc( "glTexEnviv" );
	qglTexGend = dllTexGend = ( decltype( dllTexGend ) )QGL_NullProc( "glTexGend" );
	qglTexGendv = dllTexGendv = ( decltype( dllTexGendv ) )QGL_NullProc( "glTexGendv" );
	qglTexGenf = dllTexGenf = ( decltype( dllTexGenf ) )QGL_NullProc( "glTexGenf" );
	qglTexGenfv = dllTexGenfv = ( decltype( dllTexGenfv ) )QGL_NullProc( "glTexGenfv" );
	qglTexGeni = dllTexGeni = ( decltype( dllTexGeni ) )QGL_NullProc( "glTexGeni" );
	qglTexGeniv = dllTexGeniv = ( decltype( dllTexGeniv ) )QGL_NullProc( "glTexGeniv" );
	qglTexImage1D = dllTexImage1D = ( decltype( dllTexImage1D ) )QGL_NullProc( "glTexImage1D" );
	qglTexImage2D = dllTexImage2D = ( decltype( dllTexImage2D ) )QGL_NullProc( "glTexImage2D" );
	qglTexParameterf = dllTexParameterf = ( decltype( dllTexParameterf ) )QGL_NullProc( "glTexParameterf" );
	qglTexParameterfv = dllTexParameterfv = ( decltype( dllTexParameterfv ) )QGL_NullProc( "glTexParameterfv" );
	qglTexParameteri = dllTexParameteri = ( decltype( dllTexParameteri ) )QGL_NullProc( "glTexParameteri" );
	qglTexParameteriv = dllTexParameteriv = ( decltype( dllTexParameteriv ) )QGL_NullProc( "glTexParameteriv" );
	qglTexSubImage1D = dllTexSubImage1D = ( decltype( dllTexSubImage1D ) )QGL_NullProc( "glTexSubImage1D" );
	qglTexSubImage2D = dllTexSubImage2D = ( decltype( dllTexSubImage2D ) )QGL_NullProc( "glTexSubImage2D" );
	qglTranslated = dllTranslated = ( decltype( dllTranslated ) )QGL_NullProc( "glTranslated" );
	qglTranslatef = dllTranslatef = ( decltype( dllTranslatef ) )QGL_NullProc( "glTranslatef" );
	qglVertex2d = dllVertex2d = ( decltype( dllVertex2d ) )QGL_NullProc( "glVertex2d" );
	qglVertex2dv = dllVertex2dv = ( decltype( dllVertex2dv ) )QGL_NullProc( "glVertex2dv" );
	qglVertex2f = dllVertex2f = ( decltype( dllVertex2f ) )QGL_NullProc( "glVertex2f" );
	qglVertex2fv = dllVertex2fv = ( decltype( dllVertex2fv ) )QGL_NullProc( "glVertex2fv" );
	qglVertex2i = dllVertex2i = ( decltype( dllVertex2i ) )QGL_NullProc( "glVertex2i" );
	qglVertex2iv = dllVertex2iv = ( decltype( dllVertex2iv ) )QGL_NullProc( "glVertex2iv" );
	qglVertex2s = dllVertex2s = ( decltype( dllVertex2s ) )QGL_NullProc( "glVertex2s" );
	qglVertex2sv = dllVertex2sv = ( decltype( dllVertex2sv ) )QGL_NullProc( "glVertex2sv" );
	qglVertex3d = dllVertex3d = ( decltype( dllVertex3d ) )QGL_NullProc( "glVertex3d" );
	qglVertex3dv = dllVertex3dv = ( decltype( dllVertex3dv ) )QGL_NullProc( "glVertex3dv" );
	qglVertex3f = dllVertex3f = ( decltype( dllVertex3f ) )QGL_NullProc( "glVertex3f" );
	qglVertex3fv = dllVertex3fv = ( decltype( dllVertex3fv ) )QGL_NullProc( "glVertex3fv" );
	qglVertex3i = dllVertex3i = ( decltype( dllVertex3i ) )QGL_NullProc( "glVertex3i" );
	qglVertex3iv = dllVertex3iv = ( decltype( dllVertex3iv ) )QGL_NullProc( "glVertex3iv" );
	qglVertex3s = dllVertex3s = ( decltype( dllVertex3s ) )QGL_NullProc( "glVertex3s" );
	qglVertex3sv = dllVertex3sv = ( decltype( dllVertex3sv ) )QGL_NullProc( "glVertex3sv" );
	qglVertex4d = dllVertex4d = ( decltype( dllVertex4d ) )QGL_NullProc( "glVertex4d" );
	qglVertex4dv = dllVertex4dv = ( decltype( dllVertex4dv ) )QGL_NullProc( "glVertex4dv" );
	qglVertex4f = dllVertex4f = ( decltype( dllVertex4f ) )QGL_NullProc( "glVertex4f" );
	qglVertex4fv = dllVertex4fv = ( decltype( dllVertex4fv ) )QGL_NullProc( "glVertex4fv" );
	qglVertex4i = dllVertex4i = ( decltype( dllVertex4i ) )QGL_NullProc( "glVertex4i" );
	qglVertex4iv = dllVertex4iv = ( decltype( dllVertex4iv ) )QGL_NullProc( "glVertex4iv" );
	qglVertex4s = dllVertex4s = ( decltype( dllVertex4s ) )QGL_NullProc( "glVertex4s" );
	qglVertex4sv = dllVertex4sv = ( decltype( dllVertex4sv ) )QGL_NullProc( "glVertex4sv" );
	qglVertexPointer = dllVertexPointer = ( decltype( dllVertexPointer ) )QGL_NullProc( "glVertexPointer" );
	qglViewport = dllViewport = ( decltype( dllViewport ) )QGL_NullProc( "glViewport" );

	qwglCopyContext = ( decltype( qwglCopyContext ) )QGL_NullProc( "wglCopyContext" );
	qwglCreateContext = ( decltype( qwglCreateContext ) )QGL_NullProc( "wglCreateContext" );
	qwglCreateLayerContext = ( decltype( qwglCreateLayerContext ) )QGL_NullProc( "wglCreateLayerContext" );
	qwglDeleteContext = ( decltype( qwglDeleteContext ) )QGL_NullProc( "wglDeleteContext" );
	qwglDescribeLayerPlane = ( decltype( qwglDescribeLayerPlane ) )QGL_NullProc( "wglDescribeLayerPlane" );
	qwglGetCurrentContext = ( decltype( qwglGetCurrentContext ) )QGL_NullProc( "wglGetCurrentContext" );
	qwglGetCurrentDC = ( decltype( qwglGetCurrentDC ) )QGL_NullProc( "wglGetCurrentDC" );
	qwglGetLayerPaletteEntries = ( decltype( qwglGetLayerPaletteEntries ) )QGL_NullProc( "wglGetLayerPaletteEntries" );
	qwglMakeCurrent = ( decltype( qwglMakeCurrent ) )QGL_NullProc( "wglMakeCurrent" );
	qwglRealizeLayerPalette = ( decltype( qwglRealizeLayerPalette ) )QGL_NullProc( "wglRealizeLayerPalette" );
	qwglSetLayerPaletteEntries = ( decltype( qwglSetLayerPaletteEntries ) )QGL_NullProc( "wglSetLayerPaletteEntries" );
	qwglShareLists = ( decltype( qwglShareLists ) )QGL_NullProc( "wglShareLists" );
	qwglSwapLayerBuffers = ( decltype( qwglSwapLayerBuffers ) )QGL_NullProc( "wglSwapLayerBuffers" );
	qwglUseFontBitmaps = ( decltype( qwglUseFontBitmaps ) )QGL_NullProc( "wglUseFontBitmaps" );
	qwglUseFontOutlines = ( decltype( qwglUseFontOutlines ) )QGL_NullProc( "wglUseFontOutlines" );
	qwglChoosePixelFormat = ( decltype( qwglChoosePixelFormat ) )QGL_NullProc( "ChoosePixelFormat" );
	qwglDescribePixelFormat = ( decltype( qwglDescribePixelFormat ) )QGL_NullProc( "DescribePixelFormat" );
	qwglGetPixelFormat = ( decltype( qwglGetPixelFormat ) )QGL_NullProc( "GetPixelFormat" );
	qwglSetPixelFormat = ( decltype( qwglSetPixelFormat ) )QGL_NullProc( "SetPixelFormat" );
	qwglSwapBuffers = ( decltype( qwglSwapBuffers ) )QGL_NullProc( "SwapBuffers" );

	qglGetString = dllGetString = QGL_NullGetString;
	qglGetIntegerv = dllGetIntegerv = QGL_NullGetIntegerv;
	qglGenTextures = dllGenTextures = QGL_NullGenTextures;
	qwglGetProcAddress = QGL_NullGetProcAddress;

	qglActiveTextureARB = 0;
	qglClientActiveTextureARB = 0;
	qglMultiTexCoord2fARB = 0;
	return true;
}

/* The stray-call report. Stage 9 is done when it is empty and opengl32.dll is not in the process. */
void QGL_NullReport( bool all ) {
	int total = 0, entries = 0;
	for ( int i = 0; i < qglNullCount; i++ ) {
		if ( qglNullCalls[i] ) {
			total += qglNullCalls[i];
			entries++;
		}
	}
	common->Printf( "stray OpenGL calls: %i through %i entry points; opengl32.dll is %s\n", total, entries,
		GetModuleHandle( "opengl32.dll" ) ? "LOADED" : "not loaded" );
	// most calls first
	for ( int printed = 0; printed < ( all ? entries : Min( entries, 40 ) ); printed++ ) {
		int best = -1;
		for ( int i = 0; i < qglNullCount; i++ ) {
			if ( qglNullCalls[i] > 0 && ( best < 0 || qglNullCalls[i] > qglNullCalls[best] ) ) {
				best = i;
			}
		}
		if ( best < 0 ) {
			break;
		}
		common->Printf( "  %9i  %s\n", qglNullCalls[best], qglNullNames[best] );
		qglNullCalls[best] = -qglNullCalls[best];		// printed
	}
	for ( int i = 0; i < qglNullCount; i++ ) {
		if ( qglNullCalls[i] < 0 ) {
			qglNullCalls[i] = -qglNullCalls[i];
		}
	}
}
